name: Python package

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install --upgrade build twine
      - name: Build
        run: python -m build
      - name: Test
        run: |
          pip install ./dist/*.whl
          python -m viper.examples.hello_world
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build tools
        run: pip install --upgrade build twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{sentimentaleunjun}}
          TWINE_PASSWORD: ${{A134613a!!}}
        run: twine upload dist/*
